version: "3"

tasks:
  default: task setup build run
  setup:
    - |
      ln -f ../dotfiles/starship/.config/starship.toml conf/starship.toml
  build: docker build -t tg-alpine --progress=plain .
  run: docker run -it --rm tg-alpine
